export const SHOW_HIDE_CART = 'SHOW_HIDE_CART'
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_ITEM = 'REMOVE_ITEM'
export const REMOVE_CART = 'REMOVE_CART'
export const PROGRESS_ITEM = 'PROGRESS_ITEM'
export const LOWER_ITEM = 'LOWER_ITEM'